---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: observability
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: loki
      version: 5.5.12
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: kube-prometheus-stack
      namespace: observability
    - name: promtail
      namespace: observability
  values:
    serviceMonitor:
      enabled: true
    # extraArgs:
    #   log.level: debug
    loki:
      config: |
        schema_config: 
          configs: 
            - from: 2020-10-24 
              store: boltdb-shipper 
              object_store: filesystem 
              schema: v11 
              index: 
                prefix: index_ 
                period: 24h 
        limits_config:
          enforce_metric_name: false
          reject_old_samples: true
          reject_old_samples_max_age: 168h
          ingestion_rate_mb: 16
          ingestion_burst_size_mb: 24
        storage_config:
          boltdb_shipper:
            active_index_directory: /data/loki/index
            cache_location: /data/loki/index_cache
            cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
            shared_store: filesystem
          filesystem:
            directory: /data/loki/chunks

