---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age12vp3nldqpec4lkg9qq722hl2mhzz89eyxs4gx66ngu3wcwy3j3dst2ulak
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age12vp3nldqpec4lkg9qq722hl2mhzz89eyxs4gx66ngu3wcwy3j3dst2ulak
