---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 5m
  dependsOn:
    - name: cert-manager
      namespace: core
  chart:
    spec:
      # renovate: registryUrl=https://releases.rancher.com/server-charts/latest
      chart: rancher
      sourceRef:
        kind: HelmRepository
        name: rancher-charts
        namespace: flux-system
  values:
    # Declare values passed into templates.
    hostname: rancher.karva.work 
    bootstrapPassword: admin
    global:
      cattle:
        psp:
          enabled: false