---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: code-server
  namespace: apps
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://nicholaswilde.github.io/helm-charts/
      chart: code-server
      version: 1.1.1
      sourceRef:
        kind: HelmRepository
        name: code-server-charts
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    image:
      repository: ghcr.io/linuxserver/code-server
      tag: "version-v3.11.1"
    service:
      enabled: true
      type: ClusterIP
      port:
        port: 8443
    env:
      PUID: "1000"
      PGID: "1000"
      #PROXY_DOMAIN: ${SECRET_DOMAIN}
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      hosts:
        - host: code-server.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - code-server.${SECRET_DOMAIN}
          secretName: "code-server-tls"
    persistence:
      config:
        enabled: true
        existingClaim: code-data-2
        mountPath: /config
