---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: consul
  namespace: consul
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.releases.hashicorp.com
      chart: consul
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: hashicorp-charts
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    global:
      enabled: true
      datacenter: dc1
    tls:
      enabled: true
    server:
      enabled: true
      replicas: 1
    connectInject:
      enabled: true
    ui:
      enabled: true
      service:
        enabled: true
        #type: ClusterIP
      ingress:
        enabled: true
        ingressClassName: traefik
        pathType: Prefix
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        hosts:
          - host: consul.${SECRET_DOMAIN}
            paths:
              - /
        tls: 
          - hosts:
              - consul.${SECRET_DOMAIN}
            secretName: consul-tls