---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jaeger
  namespace: observability
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://jaegertracing.github.io/helm-charts
      chart: jaeger
      version: 0.71.2
      sourceRef:
        kind: HelmRepository
        name: jaeger-charts
        namespace: flux-system
      interval: 5m
  values:
    replicas: 1
    allInOne:
      enabled: true
      image: jaegertracing/all-in-one
      tag: 1.31.0
      pullPolicy: IfNotPresent
    provisionDataStore:
      cassandra: false
    storage:
      type: none
    agent:
      enabled: false
    collector:
      enabled: false
    query:
      enabled: false
